### ISSUE TITLE
The mod sometimes prints "java.lang.NullPointerException" to the log

### ISSUE THREAD

**Issue by hiisuuii** [MrSn0wy/TeleportCommands#1]
As you can see in this log: https://mclo.gs/2PpWAVY sometimes the mod will simply log a NPE to the console. It does not print any stacktrace and it doesnt seem to cause any issue.
I have yet to be able to intentionally cause this issue. However it does seem to be caused by a player using a /home command.

**Comment by MrSn0wy** [comment]
wait i think i might've found the bug, i think it has to do with when a player dies

**Comment by hiisuuii** [comment]
> heya, thank you for the bug report!
> 
> I can't seem to replicate this issue myself and the only way this could _maybe_ trigger in the home command is if the PlayerStorage is corrupt. _(but then it should give a more detailed error message)_
> 
> Could you perhaps send the mod's storage.json that is located inside of: `[world folder]/TeleportCommands/storage.json`?

Sure thing.
[storage.json](https://github.com/user-attachments/files/16082132/storage.json)

**Comment by MrSn0wy** [comment]
Heya, sorry for the 5 month radio silence.

I looked at the storage a while back and couldnt find anything strange about it, i also ran a fabric server with my friends for a bit with the mod and never was able to reproduce this so i didnt really know how to fix this issue.

However in the new 1.2.0 (and higher) release of the mod i have improved the error logging by alot (as you might've seen it was really bad before lmao) so if you get the issue again on newer versions of the mod please let me know and send me a sever log! This time i will most likely be able to find out what actually happend x3

I will try to backport all the changes slowely to the older minecraft versions.

**Comment by rrgeorge** [comment]
If it helps, I am using NeoForge with Geyser installed to allow for Bedrock players

**Comment by MrSn0wy** [comment]
Man i really have no clue what could case this. Can you tell me what version of the mod you have and the minecraft version? Also maybe you can figure out what command caused it?
Thanks in advance!

**Comment by rrgeorge** [comment]
I'm running 1.21.4 with neoforge-21.4.30-beta and the Teleport Commands version neoforge-1.21.4-1.2.1 (latest from modrinth). I'm only using `/home`, which is what triggers the error, although the command appears to work just fine.

Looking at the log posted by OP, one of the users has a `~` prefix on their name, likely indicating that they're also using Geyser to allow bedrock players. So I had an idea.. I usually play on bedrock as well, and just tested it.. I connected using the java client and was able to use `/home` without triggering the error.  So it looks to me like the error is only caused by users that are connected via geyser. I'm not sure what exactly is different about those players, (maybe there's some attribute you're trying to read that's just not set?), but hopefully that can point you in the right direction.

**Comment by MrSn0wy** [comment]
Thank you so much for pointing me in the right direction! I managed to fix it and discover two bugs in the process.

First geyser returns the client's language as uppercase instead of lowercase like on java, i fixed this by just making the value lowercase.

The second issue is that I apparently forgot to remove an error logging function when a language file can't be found.... (yeah.. my bad). And because that geyser returns the language in the wrong format (uppercase) it appeared to happen only on geyser. Of course nothing seemed to be wrong since after not finding the language file it falls back to the default English file.

I will upload a new release in a few days, however if you want you can download the jar file from the github actions in the mean time.

**Comment by rrgeorge** [comment]
Oh that’s interesting. I wonder if a bug should be filed with geyser then, since that’s inconsistent with Java?
I suspected it was a relatively benign error, since it didn’t seem to actually affect the functionality. I’m glad I could help.
